package com.google.android.gms.internal;

import android.content.Context;
import com.facebook.appevents.AppEventsConstants;
import io.reactivex.annotations.SchedulerSupport;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;
@zzji
/* loaded from: classes.dex */
public final class zzdr {
    public static final zzdn<String> zzbcw = zzdn.zza(0, "gads:sdk_core_experiment_id");
    public static final zzdn<String> zzbcx = zzdn.zza(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    public static final zzdn<Boolean> zzbcy = zzdn.zza(0, "gads:request_builder:singleton_webview", (Boolean) false);
    public static final zzdn<String> zzbcz = zzdn.zza(0, "gads:request_builder:singleton_webview_experiment_id");
    public static final zzdn<Boolean> zzbda = zzdn.zza(0, "gads:sdk_use_dynamic_module", (Boolean) true);
    public static final zzdn<String> zzbdb = zzdn.zza(0, "gads:sdk_use_dynamic_module_experiment_id");
    public static final zzdn<Boolean> zzbdc = zzdn.zza(0, "gads:sdk_crash_report_enabled", (Boolean) false);
    public static final zzdn<Boolean> zzbdd = zzdn.zza(0, "gads:sdk_crash_report_full_stacktrace", (Boolean) false);
    public static final zzdn<String> zzbde = zzdn.zza(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final zzdn<Boolean> zzbdf = zzdn.zza(0, "gads:block_autoclicks", (Boolean) false);
    public static final zzdn<String> zzbdg = zzdn.zza(0, "gads:block_autoclicks_experiment_id");
    public static final zzdn<String> zzbdh = zzdn.zzb(0, "gads:prefetch:experiment_id");
    public static final zzdn<String> zzbdi = zzdn.zza(0, "gads:spam_app_context:experiment_id");
    public static final zzdn<Boolean> zzbdj = zzdn.zza(1, "gads:spam_app_context:enabled", (Boolean) false);
    public static final zzdn<Integer> zzbdk = zzdn.zza(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final zzdn<String> zzbdl = zzdn.zza(1, "gads:video_exo_player:version", AppEventsConstants.EVENT_PARAM_VALUE_YES);
    public static final zzdn<String> zzbdm = zzdn.zza(0, "gads:video_stream_cache:experiment_id");
    public static final zzdn<Integer> zzbdn = zzdn.zza(1, "gads:video_stream_cache:limit_count", 5);
    public static final zzdn<Integer> zzbdo = zzdn.zza(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzdn<Integer> zzbdp = zzdn.zza(1, "gads:video_stream_exo_allocator:segment_size", 65536);
    public static final zzdn<Integer> zzbdq = zzdn.zza(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzdn<Long> zzbdr = zzdn.zza(1, "gads:video_stream_cache:limit_time_sec", 300L);
    public static final zzdn<Long> zzbds = zzdn.zza(1, "gads:video_stream_cache:notify_interval_millis", 1000L);
    public static final zzdn<Integer> zzbdt = zzdn.zza(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final zzdn<Boolean> zzbdu = zzdn.zza(0, "gads:video:metric_reporting_enabled", (Boolean) false);
    public static final zzdn<String> zzbdv = zzdn.zza(1, "gads:video:metric_frame_hash_times", "");
    public static final zzdn<Long> zzbdw = zzdn.zza(1, "gads:video:metric_frame_hash_time_leniency", 500L);
    public static final zzdn<Boolean> zzbdx = zzdn.zza(1, "gads:video:force_watermark", (Boolean) false);
    public static final zzdn<Long> zzbdy = zzdn.zza(1, "gads:video:surface_update_min_spacing_ms", 1000L);
    public static final zzdn<Boolean> zzbdz = zzdn.zza(1, "gads:video:spinner:enabled", (Boolean) false);
    public static final zzdn<Integer> zzbea = zzdn.zza(1, "gads:video:spinner:scale", 4);
    public static final zzdn<Long> zzbeb = zzdn.zza(1, "gads:video:spinner:jank_threshold_ms", 50L);
    public static final zzdn<Boolean> zzbec = zzdn.zza(1, "gads:memory_bundle:debug_info", (Boolean) false);
    public static final zzdn<Boolean> zzbed = zzdn.zza(1, "gads:memory_bundle:runtime_info", (Boolean) true);
    public static final zzdn<String> zzbee = zzdn.zzb(0, "gads:spam_ad_id_decorator:experiment_id");
    public static final zzdn<Boolean> zzbef = zzdn.zza(0, "gads:spam_ad_id_decorator:enabled", (Boolean) false);
    public static final zzdn<Boolean> zzbeg = zzdn.zza(0, "gads:ad_id_app_context:enabled", (Boolean) false);
    public static final zzdn<Float> zzbeh = zzdn.zza(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
    public static final zzdn<String> zzbei = zzdn.zza(0, "gads:ad_id_app_context:experiment_id");
    public static final zzdn<String> zzbej = zzdn.zzb(0, "gads:looper_for_gms_client:experiment_id");
    public static final zzdn<Boolean> zzbek = zzdn.zza(0, "gads:looper_for_gms_client:enabled", (Boolean) true);
    public static final zzdn<Boolean> zzbel = zzdn.zza(0, "gads:sw_ad_request_service:enabled", (Boolean) true);
    public static final zzdn<Boolean> zzbem = zzdn.zza(0, "gads:sw_dynamite:enabled", (Boolean) true);
    public static final zzdn<String> zzben = zzdn.zza(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final zzdn<String> zzbeo = zzdn.zza(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final zzdn<String> zzbep = zzdn.zza(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final zzdn<Boolean> zzbeq = zzdn.zza(0, "gads:enabled_sdk_csi", (Boolean) false);
    public static final zzdn<String> zzber = zzdn.zza(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final zzdn<Boolean> zzbes = zzdn.zza(0, "gads:sdk_csi_write_to_file", (Boolean) false);
    public static final zzdn<Boolean> zzbet = zzdn.zza(1, "gads:use_adx_javascript_adapter", (Boolean) false);
    public static final zzdn<Boolean> zzbeu = zzdn.zza(0, "gads:enable_content_fetching", (Boolean) true);
    public static final zzdn<Integer> zzbev = zzdn.zza(0, "gads:content_length_weight", 1);
    public static final zzdn<Integer> zzbew = zzdn.zza(0, "gads:content_age_weight", 1);
    public static final zzdn<Integer> zzbex = zzdn.zza(0, "gads:min_content_len", 11);
    public static final zzdn<Integer> zzbey = zzdn.zza(0, "gads:fingerprint_number", 10);
    public static final zzdn<Integer> zzbez = zzdn.zza(0, "gads:sleep_sec", 10);
    public static final zzdn<Boolean> zzbfa = zzdn.zza(1, "gads:enable_content_url_hash", (Boolean) true);
    public static final zzdn<Integer> zzbfb = zzdn.zza(1, "gads:content_vertical_fingerprint_number", 100);
    public static final zzdn<Boolean> zzbfc = zzdn.zza(1, "gads:enable_content_vertical_hash", (Boolean) true);
    public static final zzdn<Integer> zzbfd = zzdn.zza(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final zzdn<Integer> zzbfe = zzdn.zza(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final zzdn<String> zzbff = zzdn.zza(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final zzdn<String> zzbfg = zzdn.zza(1, "gads:content_fetch_exclude_view_tag", SchedulerSupport.NONE);
    public static final zzdn<Boolean> zzbfh = zzdn.zza(0, "gad:app_index_enabled", (Boolean) true);
    public static final zzdn<Boolean> zzbfi = zzdn.zza(0, "gads:app_index:without_content_info_present:enabled", (Boolean) true);
    public static final zzdn<Long> zzbfj = zzdn.zza(0, "gads:app_index:timeout_ms", 1000L);
    public static final zzdn<String> zzbfk = zzdn.zza(0, "gads:app_index:experiment_id");
    public static final zzdn<String> zzbfl = zzdn.zza(0, "gads:kitkat_interstitial_workaround:experiment_id");
    public static final zzdn<Boolean> zzbfm = zzdn.zza(0, "gads:kitkat_interstitial_workaround:enabled", (Boolean) true);
    public static final zzdn<Boolean> zzbfn = zzdn.zza(0, "gads:interstitial_follow_url", (Boolean) true);
    public static final zzdn<Boolean> zzbfo = zzdn.zza(0, "gads:interstitial_follow_url:register_click", (Boolean) true);
    public static final zzdn<String> zzbfp = zzdn.zza(0, "gads:interstitial_follow_url:experiment_id");
    public static final zzdn<Boolean> zzbfq = zzdn.zza(0, "gads:analytics_enabled", (Boolean) true);
    public static final zzdn<Boolean> zzbfr = zzdn.zza(0, "gads:ad_key_enabled", (Boolean) false);
    public static final zzdn<Integer> zzbfs = zzdn.zza(0, "gads:webview_cache_version", 0);
    public static final zzdn<Boolean> zzbft = zzdn.zza(1, "gads:webview_recycle:enabled", (Boolean) false);
    public static final zzdn<String> zzbfu = zzdn.zza(1, "gads:webview_recycle:experiment_id");
    public static final zzdn<Boolean> zzbfv = zzdn.zza(1, "gads:webview:ignore_over_scroll", (Boolean) true);
    public static final zzdn<String> zzbfw = zzdn.zzb(0, "gads:pan:experiment_id");
    public static final zzdn<String> zzbfx = zzdn.zza(1, "gads:rewarded:experiment_id");
    public static final zzdn<Long> zzbfy = zzdn.zza(1, "gads:rewarded:adapter_timeout_ms", 20000L);
    public static final zzdn<Boolean> zzbfz = zzdn.zza(1, "gads:app_activity_tracker:enabled", (Boolean) true);
    public static final zzdn<Long> zzbga = zzdn.zza(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
    public static final zzdn<Long> zzbgb = zzdn.zza(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final zzdn<Boolean> zzbgc = zzdn.zza(0, "gads:ad_serving:enabled", (Boolean) true);
    public static final zzdn<String> zzbgd = zzdn.zza(1, "gads:ad_manager_enforce_arp_invariant:experiment_id");
    public static final zzdn<Boolean> zzbge = zzdn.zza(1, "gads:ad_manager_enforce_arp_invariant:enabled", (Boolean) false);
    public static final zzdn<Long> zzbgf = zzdn.zza(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000L);
    public static final zzdn<Boolean> zzbgg = zzdn.zza(1, "gads:interstitial_ad_pool:enabled", (Boolean) false);
    public static final zzdn<Boolean> zzbgh = zzdn.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean) false);
    public static final zzdn<String> zzbgi = zzdn.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final zzdn<String> zzbgj = zzdn.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final zzdn<Integer> zzbgk = zzdn.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final zzdn<Integer> zzbgl = zzdn.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final zzdn<Integer> zzbgm = zzdn.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final zzdn<String> zzbgn = zzdn.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final zzdn<String> zzbgo = zzdn.zza(1, "gads:spherical_video:vertex_shader", "");
    public static final zzdn<String> zzbgp = zzdn.zza(1, "gads:spherical_video:fragment_shader", "");
    public static final zzdn<String> zzbgq = zzdn.zza(1, "gads:spherical_video:experiment_id");
    public static final zzdn<Boolean> zzbgr = zzdn.zza(0, "gads:log:verbose_enabled", (Boolean) false);
    public static final zzdn<Boolean> zzbgs = zzdn.zza(1, "gads:include_local_global_rectangles", (Boolean) false);
    public static final zzdn<String> zzbgt = zzdn.zza(1, "gads:include_local_global_rectangles:experiment_id");
    public static final zzdn<Long> zzbgu = zzdn.zza(1, "gads:position_watcher:throttle_ms", 200L);
    public static final zzdn<Boolean> zzbgv = zzdn.zza(0, "gads:device_info_caching:enabled", (Boolean) true);
    public static final zzdn<Long> zzbgw = zzdn.zza(0, "gads:device_info_caching_expiry_ms:expiry", 300000L);
    public static final zzdn<Boolean> zzbgx = zzdn.zza(0, "gads:gen204_signals:enabled", (Boolean) false);
    public static final zzdn<Boolean> zzbgy = zzdn.zza(0, "gads:webview:error_reporting_enabled", (Boolean) false);
    public static final zzdn<Boolean> zzbgz = zzdn.zza(0, "gads:adid_reporting:enabled", (Boolean) false);
    public static final zzdn<Boolean> zzbha = zzdn.zza(0, "gads:ad_settings_page_reporting:enabled", (Boolean) false);
    public static final zzdn<Boolean> zzbhb = zzdn.zza(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", (Boolean) false);
    public static final zzdn<Boolean> zzbhc = zzdn.zza(0, "gads:request_pkg:enabled", (Boolean) true);
    public static final zzdn<Boolean> zzbhd = zzdn.zza(1, "gads:gmsg:disable_back_button:enabled", (Boolean) true);
    public static final zzdn<Boolean> zzbhe = zzdn.zza(0, "gads:gmsg:video_meta:enabled", (Boolean) true);
    public static final zzdn<String> zzbhf = zzdn.zza(0, "gads:gmsg:video_meta:experiment_id");
    public static final zzdn<Long> zzbhg = zzdn.zza(0, "gads:network:cache_prediction_duration_s", 300L);
    public static final zzdn<Boolean> zzbhh = zzdn.zza(0, "gads:mediation:dynamite_first:admobadapter", (Boolean) true);
    public static final zzdn<Boolean> zzbhi = zzdn.zza(0, "gads:mediation:dynamite_first:adurladapter", (Boolean) true);
    public static final zzdn<Long> zzbhj = zzdn.zza(0, "gads:ad_loader:timeout_ms", 60000L);
    public static final zzdn<Long> zzbhk = zzdn.zza(0, "gads:rendering:timeout_ms", 60000L);
    public static final zzdn<Boolean> zzbhl = zzdn.zza(0, "gads:adshield:enable_adshield_instrumentation", (Boolean) false);
    public static final zzdn<Long> zzbhm = zzdn.zza(1, "gads:gestures:task_timeout", 2000L);
    public static final zzdn<String> zzbhn = zzdn.zza(1, "gads:gestures:encrypt_size_limit:experiment_id");
    public static final zzdn<Boolean> zzbho = zzdn.zza(1, "gads:gestures:encrypt_size_limit:enabled", (Boolean) false);
    public static final zzdn<String> zzbhp = zzdn.zza(1, "gads:gestures:appid:experiment_id");
    public static final zzdn<Boolean> zzbhq = zzdn.zza(1, "gads:gestures:appid:enabled", (Boolean) false);
    public static final zzdn<Boolean> zzbhr = zzdn.zza(0, "gads:gestures:v6:enabled", (Boolean) false);
    public static final zzdn<String> zzbhs = zzdn.zza(1, "gads:gestures:usb_query:experiment_id");
    public static final zzdn<Boolean> zzbht = zzdn.zza(1, "gads:gestures:usb_query:enabled", (Boolean) false);
    public static final zzdn<String> zzbhu = zzdn.zza(1, "gads:gestures:usb_click:experiment_id");
    public static final zzdn<Boolean> zzbhv = zzdn.zza(1, "gads:gestures:usb_click:enabled", (Boolean) false);
    public static final zzdn<Boolean> zzbhw = zzdn.zza(1, "gads:gestures:touchinfo:enabled", (Boolean) false);
    public static final zzdn<String> zzbhx = zzdn.zza(1, "gads:gestures:touchinfo:experiment_id");
    public static final zzdn<Boolean> zzbhy = zzdn.zza(1, "gads:gestures:clock_query:enabled", (Boolean) false);
    public static final zzdn<String> zzbhz = zzdn.zza(1, "gads:gestures:clock_query:experiment_id");
    public static final zzdn<Boolean> zzbia = zzdn.zza(1, "gads:gestures:clock_click:enabled", (Boolean) false);
    public static final zzdn<String> zzbib = zzdn.zza(1, "gads:gestures:clock_click:experiment_id");
    public static zzdn<Boolean> zzbic = zzdn.zza(1, "gads:gestures:btl_click:enabled", (Boolean) false);
    public static zzdn<String> zzbid = zzdn.zza(1, "gads:gestures:btl_click:experiment_id");
    public static final zzdn<String> zzbie = zzdn.zza(1, "gads:gestures:click_stk:experiment_id");
    public static final zzdn<Boolean> zzbif = zzdn.zza(1, "gads:gestures:click_stk:enabled", (Boolean) true);
    public static final zzdn<Boolean> zzbig = zzdn.zza(1, "gads:gestures:visibility:enabled", (Boolean) false);
    public static final zzdn<Boolean> zzbih = zzdn.zza(1, "gads:gestures:check_initialization_thread:enabled", (Boolean) false);
    public static final zzdn<Boolean> zzbii = zzdn.zza(1, "gads:gestures:get_query_in_non_ui_thread:enabled", (Boolean) true);
    public static final zzdn<Boolean> zzbij = zzdn.zza(0, "gass:client:enabled", (Boolean) true);
    public static final zzdn<String> zzbik = zzdn.zza(0, "gass:client:experiment_id");
    public static final zzdn<Boolean> zzbil = zzdn.zza(0, "gass:enabled", (Boolean) true);
    public static final zzdn<Boolean> zzbim = zzdn.zza(0, "gass:enable_int_signal", (Boolean) true);
    public static final zzdn<Boolean> zzbin = zzdn.zza(0, "gads:adid_notification:first_party_check:enabled", (Boolean) true);
    public static final zzdn<Boolean> zzbio = zzdn.zza(0, "gads:edu_device_helper:enabled", (Boolean) true);
    public static final zzdn<Boolean> zzbip = zzdn.zza(0, "gads:support_screen_shot", (Boolean) true);
    public static final zzdn<Boolean> zzbiq = zzdn.zza(0, "gads:use_get_drawing_cache_for_screenshot:enabled", (Boolean) true);
    public static final zzdn<String> zzbir = zzdn.zza(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    public static final zzdn<String> zzbis = zzdn.zza(1, "gads:sdk_core_constants:experiment_id");
    public static final zzdn<String> zzbit = zzdn.zza(1, "gads:sdk_core_constants:caps", "");
    public static final zzdn<Long> zzbiu = zzdn.zza(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final zzdn<Boolean> zzbiv = zzdn.zza(0, "gads:js_flags:mf", (Boolean) false);
    public static final zzdn<Boolean> zzbiw = zzdn.zza(0, "gads:custom_render:ping_on_ad_rendered", (Boolean) false);
    public static final zzdn<String> zzbix = zzdn.zza(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final zzdn<String> zzbiy = zzdn.zza(1, "gads:native:video_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
    public static final zzdn<Boolean> zzbiz = zzdn.zza(1, "gads:singleton_webview_native", (Boolean) false);
    public static final zzdn<String> zzbja = zzdn.zza(1, "gads:singleton_webview_native:experiment_id");
    public static final zzdn<Boolean> zzbjb = zzdn.zza(1, "gads:enable_untrack_view_native", (Boolean) true);
    public static final zzdn<Boolean> zzbjc = zzdn.zza(1, "gads:ignore_untrack_view_google_native", (Boolean) true);
    public static final zzdn<Boolean> zzbjd = zzdn.zza(1, "gads:reset_listeners_preparead_native", (Boolean) true);
    public static final zzdn<Integer> zzbje = zzdn.zza(1, "gads:native_video_load_timeout", 10);
    public static final zzdn<String> zzbjf = zzdn.zza(1, "gads:native_video_load_timeout:experiment_id");
    public static final zzdn<String> zzbjg = zzdn.zza(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final zzdn<Boolean> zzbjh = zzdn.zza(1, "gads:clamp_native_video_player_dimensions", (Boolean) true);
    public static final zzdn<Boolean> zzbji = zzdn.zza(1, "gads:enable_tracking_for_native_ad_views", (Boolean) true);
    public static final zzdn<Boolean> zzbjj = zzdn.zza(1, "gads:use_new_json_for_native_view_tracking", (Boolean) true);
    public static final zzdn<Boolean> zzbjk = zzdn.zza(1, "gads:fluid_ad:use_wrap_content_height", (Boolean) false);
    public static final zzdn<Boolean> zzbjl = zzdn.zza(0, "gads:method_tracing:enabled", (Boolean) false);
    public static final zzdn<Long> zzbjm = zzdn.zza(0, "gads:method_tracing:duration_ms", 30000L);
    public static final zzdn<Integer> zzbjn = zzdn.zza(0, "gads:method_tracing:count", 5);
    public static final zzdn<Integer> zzbjo = zzdn.zza(0, "gads:method_tracing:filesize", 134217728);
    public static final zzdn<Boolean> zzbjp = zzdn.zza(1, "gads:auto_location_for_coarse_permission", (Boolean) false);
    public static final zzdn<String> zzbjq = zzdn.zzb(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final zzdn<Long> zzbjr = zzdn.zza(1, "gads:auto_location_timeout", 2000L);
    public static final zzdn<String> zzbjs = zzdn.zzb(1, "gads:auto_location_timeout:experiment_id");
    public static final zzdn<Long> zzbjt = zzdn.zza(1, "gads:auto_location_interval", -1L);
    public static final zzdn<String> zzbju = zzdn.zzb(1, "gads:auto_location_interval:experiment_id");
    public static final zzdn<Boolean> zzbjv = zzdn.zza(1, "gads:fetch_app_settings_using_cld:enabled", (Boolean) false);
    public static final zzdn<String> zzbjw = zzdn.zza(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    public static final zzdn<Long> zzbjx = zzdn.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
    public static final zzdn<String> zzbjy = zzdn.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms:experiment_id");
    public static final zzdn<String> zzbjz = zzdn.zza(0, "gads:afs:csa:experiment_id");
    public static final zzdn<String> zzbka = zzdn.zza(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final zzdn<String> zzbkb = zzdn.zza(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final zzdn<String> zzbkc = zzdn.zza(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final zzdn<String> zzbkd = zzdn.zza(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final zzdn<String> zzbke = zzdn.zza(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final zzdn<Long> zzbkf = zzdn.zza(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000L);
    public static final zzdn<Boolean> zzbkg = zzdn.zza(0, "gads:afs:csa_ad_manager_enabled", (Boolean) true);
    public static final zzdn<Boolean> zzbkh = zzdn.zza(1, "gads:parental_controls:send_from_client", (Boolean) true);
    public static final zzdn<Boolean> zzbki = zzdn.zza(1, "gads:parental_controls:cache_results", (Boolean) true);
    public static final zzdn<Long> zzbkj = zzdn.zza(1, "gads:parental_controls:timeout", 2000L);
    public static final zzdn<String> zzbkk = zzdn.zza(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    public static final zzdn<Long> zzbkl = zzdn.zza(0, "gads:safe_browsing:safety_net:delay_ms", 2000L);
    public static final zzdn<Boolean> zzbkm = zzdn.zza(0, "gads:safe_browsing:debug", (Boolean) false);
    public static final zzdn<Boolean> zzbkn = zzdn.zza(0, "gads:webview_cookie:enabled", (Boolean) true);
    public static final zzdn<Integer> zzbko = zzdn.zza(1, "gads:cache:max_concurrent_downloads", 10);
    public static final zzdn<Long> zzbkp = zzdn.zza(1, "gads:cache:javascript_timeout_millis", 5000L);
    public static final zzdn<Boolean> zzbkq = zzdn.zza(1, "gads:cache:bind_on_foreground", (Boolean) false);
    public static final zzdn<Boolean> zzbkr = zzdn.zza(1, "gads:cache:bind_on_init", (Boolean) false);
    public static final zzdn<Boolean> zzbks = zzdn.zza(1, "gads:cache:bind_on_request", (Boolean) false);
    public static final zzdn<Long> zzbkt = zzdn.zza(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final zzdn<Boolean> zzbku = zzdn.zza(1, "gads:cache:use_cache_data_source", (Boolean) false);
    public static final zzdn<Boolean> zzbkv = zzdn.zza(1, "gads:chrome_custom_tabs:enabled", (Boolean) true);
    public static final zzdn<Boolean> zzbkw = zzdn.zza(1, "gads:drx_in_app_preview:enabled", (Boolean) false);
    public static final zzdn<Boolean> zzbkx = zzdn.zza(1, "gads:drx_debug_signals:enabled", (Boolean) false);
    public static final zzdn<String> zzbky = zzdn.zza(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final zzdn<String> zzbkz = zzdn.zza(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final zzdn<String> zzbla = zzdn.zza(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final zzdn<String> zzblb = zzdn.zza(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final zzdn<Integer> zzblc = zzdn.zza(1, "gads:drx_debug:timeout_ms", 5000);
    public static final zzdn<Integer> zzbld = zzdn.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final zzdn<Boolean> zzble = zzdn.zza(1, "gad:interstitial_for_multi_window", (Boolean) false);
    public static final zzdn<Boolean> zzblf = zzdn.zza(1, "gad:interstitial_ad_stay_active_in_multi_window", (Boolean) false);

    public static void initialize(final Context context) {
        zzlo.zzb(new Callable<Void>() { // from class: com.google.android.gms.internal.zzdr.1
            @Override // java.util.concurrent.Callable
            /* renamed from: zzdo */
            public Void call() {
                com.google.android.gms.ads.internal.zzu.zzgy().initialize(context);
                return null;
            }
        });
    }

    public static List<String> zzlq() {
        return com.google.android.gms.ads.internal.zzu.zzgx().zzlq();
    }

    public static List<String> zzlr() {
        return com.google.android.gms.ads.internal.zzu.zzgx().zzlr();
    }
}
